<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrainerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trainers')->truncate();
        DB::table('trainers')->insert([
            [
                'name' => 'Nguyễn Văn Hùng',
                'email' => 'hung.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0901234567',
                'date_of_birth' => '1990-05-12',
                'gender' => 0,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9v97bAbcmpOOkK5B-0dHpunzMJ_jsAail7t9vWYtlMw&s=10',
                'experience' => 5,
                'specialization' => 'Strength Training, Weight Loss',
                'address' => 'Đà Nẵng',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trần Thị Mai',
                'email' => 'mai.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0912345678',
                'date_of_birth' => '1995-09-20',
                'gender' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY__S4Si_awG6WODh6MjeRfcNqZKCTtyUIFknSq6oFiv2LibjxN-vifGnN&s=10',
                'experience' => 3,
                'specialization' => 'Yoga, Weight Loss',
                'address' => 'Quảng Nam',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lê Hoàng Nam',
                'email' => 'nam.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0923456789',
                'date_of_birth' => '1988-03-15',
                'gender' => 0,
                'avatar' => 'https://png.pngtree.com/png-clipart/20240628/original/pngtree-gym-boy-png-image_15429062.png',
                'experience' => 7,
                'specialization' => 'Muscle Gain, Strength Training',
                'address' => 'Huế',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phạm Thị Lan',
                'email' => 'lan.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0934567890',
                'date_of_birth' => '1992-11-05',
                'gender' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIjK3HR02bhC8pOF7Ngyd8KA2anHVqeb8gUQcUpLJ10JyBygFkZMErnvo&s=10',
                'experience' => 4,
                'specialization' => 'Fitness, Weight Loss',
                'address' => 'Đà Nẵng',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đặng Quốc Bảo',
                'email' => 'bao.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0945678901',
                'date_of_birth' => '1991-07-08',
                'gender' => 0,
                'avatar' => 'https://thumbs.dreamstime.com/b/reference-image-upscaled-gigapixel-v-ppi-model-high-fidelity-denoise-sharpen-decompression-413537127.jpg',
                'experience' => 6,
                'specialization' => 'Bodybuilding, HIIT',
                'address' => 'Quảng Nam',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Võ Thị Hạnh',
                'email' => 'hanh.pt@gym.com',
                'password' => bcrypt('123456'),
                'phone' => '0956789012',
                'date_of_birth' => '1996-02-28',
                'gender' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR68LuwxsVd0Dupki2n9Gq_PiSg7_DwA1mXpvKde4JFs1m-oUQp4dE9zBMY&s=10',
                'experience' => 4,
                'specialization' => 'Yoga, Pilates, Rehabilitation',
                'address' => 'Đà Nẵng',
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'status' => 1,
                'id_branch' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
